version: "3.8"

services:
  payments-and-suscription-mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: payments-and-suscription-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - socialbeats-network
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db

  payments-and-suscription:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: payments-and-suscription
    environment:
      - MONGOURL=${MONGOURL}
      - MONGOADMIN=${MONGOADMIN}
      - MONGOPASS=${MONGOPASS}
      - NODE_ENV=development
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - JWT_SECRET=${JWT_SECRET}
      - API_TITLE=${API_TITLE}
      - API_DESCRIPTION=${API_DESCRIPTION}
    depends_on:
      - payments-and-suscription-mongodb
    networks:
      - socialbeats-network
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app:cached
      - /app/node_modules
    command: nodemon --watch /app --legacy-watch --polling-interval 1000 main.js

volumes:
  mongo-data:

networks:
  socialbeats-network:
    external: true
